[project]
name = "boardgame-detecor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc[gdrive]>=3.65.0",
    "numpy>=1.26.0",
    "opencv-contrib-python>=4.8.0",
]

[tool.uv]
dev-dependencies = []